// Pulls the abi and the deployed addresses straight out of the foundry build,
// so the app can never drift from the contracts sitting next to it.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contracts = resolve(here, "../../contracts");
const CHAIN_ID = 1301;

function artifact(name) {
  const p = resolve(contracts, `out/${name}.sol/${name}.json`);
  if (!existsSync(p)) throw new Error(`missing artifact ${p}, run: forge build`);
  return JSON.parse(readFileSync(p, "utf8")).abi;
}

// generated.ts is committed so the app builds from a clean clone without
// foundry. if the artifacts are not here, keep whatever is already generated.
function bailIfNoArtifacts() {
  const probe = resolve(contracts, "out/ImpactRebatedFees.sol/ImpactRebatedFees.json");
  const existing = resolve(here, "../lib/generated.ts");
  if (!existsSync(probe) && existsSync(existing)) {
    console.log("no foundry artifacts, keeping the committed lib/generated.ts");
    process.exit(0);
  }
}
bailIfNoArtifacts();

const deploymentPath = resolve(contracts, `deployments/${CHAIN_ID}.json`);
if (!existsSync(deploymentPath)) throw new Error(`no deployment for ${CHAIN_ID}`);
const d = JSON.parse(readFileSync(deploymentPath, "utf8"));

// the rpc caps eth_getLogs at 10k blocks, so the app needs a floor to page back to
let deployedAt = 0;
const runPath = resolve(contracts, `broadcast/Deploy.s.sol/${CHAIN_ID}/run-latest.json`);
if (existsSync(runPath)) {
  const run = JSON.parse(readFileSync(runPath, "utf8"));
  const blocks = (run.receipts ?? []).map((r) =>
    typeof r.blockNumber === "string" ? parseInt(r.blockNumber, 16) : r.blockNumber,
  );
  if (blocks.length) deployedAt = Math.min(...blocks);
}

const out = `// generated by scripts/sync-abi.mjs, do not edit
export const chainId = ${CHAIN_ID} as const;

export const addresses = {
  hook: "${d.hook}",
  poolManager: "${d.poolManager}",
  swapRouter: "${d.swapRouter}",
  modifyLiquidityRouter: "${d.modifyLiquidityRouter}",
  currency0: "${d.currency0}",
  currency1: "${d.currency1}",
} as const;

export const poolKey = {
  currency0: "${d.currency0}",
  currency1: "${d.currency1}",
  fee: ${d.fee},
  tickSpacing: ${d.tickSpacing},
  hooks: "${d.hook}",
} as const;

export const poolId = "${d.poolId}" as const;

export const deployedAtBlock = ${deployedAt}n;
export const maxLogSpan = 10_000n;

export const hookAbi = ${JSON.stringify(artifact("ImpactRebatedFees"), null, 2)} as const;

export const swapRouterAbi = ${JSON.stringify(artifact("PoolSwapTest"), null, 2)} as const;

export const erc20Abi = ${JSON.stringify(artifact("MockERC20"), null, 2)} as const;
`;

writeFileSync(resolve(here, "../lib/generated.ts"), out);

// the evidence screen reads the analysis output, so copy it in rather than
// letting the app carry a second, drifting set of numbers
const econ = resolve(here, "../../analysis/out/economics.json");
if (existsSync(econ)) {
  writeFileSync(resolve(here, "../data/economics.json"), readFileSync(econ));
  console.log("copied analysis/out/economics.json");
}
console.log(`synced hook ${d.hook} on chain ${CHAIN_ID}`);
